Models/Cat.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CatBlog.Models
{
    public class Cat
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Age { get; set; }
        public string Color { get; set; }

        public string BestFail { get; set; }
    }
}

Models/CatBlogContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace CatBlog.Models
{
    public class CatBlogContext : IdentityDbContext
    {
        public CatBlogContext(DbContextOptions<CatBlogContext> options)
            : base(options)
        {
        }

        public DbSet<Cat> Cat { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace CatBlog.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace CatBlog.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new CatBlogContext(
                serviceProvider.GetRequiredService<DbContextOptions<CatBlogContext>>()))
            {
                // Look for any cats.
                if (context.Cat.Any())
                {
                    return;   // DB has been seeded
                }

                context.Cat.AddRange(
                    new Cat
                    {
                        Name = "Mio Bonsai",
                        Age = 2,
                        Color = "black and white",
                        BestFail = "Taken by the police"
                    },

                    new Cat
                    {
                        Name = "Felix",
                        Age = 18,
                        Color = "Tiger",
                        BestFail = "Stealing candy"
                    },

                    new Cat
                    {
                        Name = "Nacho",
                        Age = 9,
                        Color = "black and white",
                        BestFail = "Bankrobery"
                    },

                    new Cat
                    {
                        Name = "Roxy",
                        Age = 4,
                        Color = "black",
                        BestFail = "Cursing everybody"
                    }
                );
                context.SaveChanges();
            }
        }
    }
}

Controllers/CatController.cs
using Microsoft.AspNetCore.Mvc;
using CatBlog.Models;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace CatBlog.Controllers
{
    public class CatController : Controller
    {
        private readonly CatBlogContext _context;

        public CatController(CatBlogContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            var cats = await _context.Cat.ToListAsync();
            return View(cats);
        }

        [HttpPost]
        public async Task<IActionResult> Post(Cat newCat)
        {
            _context.Cat.Add(newCat);
            await _context.SaveChangesAsync();
            return Redirect("/");
        }

        [HttpDelete("/cat/delete/{catId}")]
        public async Task<IActionResult> Delete(int catId) {
            var catToRemove = await _context.Cat.FindAsync(catId);
            _context.Cat.Remove(catToRemove);
            await _context.SaveChangesAsync();
            return Redirect("/");
        }
    }
}

Views/Cat/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<CatBlog.Models.Cat>
@inject SignInManager<IdentityUser> SignInManager
@{
    ViewData["Title"] = "Home Page";
}

@if (SignInManager.IsSignedIn(User))
{
    <div class="text-center">
        <div class="container">
            <h1 class="is-size-2 has-text-weight-bold">Welcome to Mio's Cat Blog!</h1>

            <h3 class="is-size-4 has-text-weight-bold">Hi, I'm Mio, and I'm the master of desaster.</h3>
            <p>In my Blog, I'will share my daly fails with my lovely community and it would be very nice, to hear also what's happend to you.</p>
            <p>Try to beat me, but that will be hard, good luck and stay safe!</p>
        </div>
        <br>
        <table class="table">

            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Color)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Age)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BestFail)
                    </th>
                </tr>
            </thead>
            <tbody>
            @foreach (var cat in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => cat.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => cat.Color)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => cat.Age)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => cat.BestFail)
                    </td>
                    <td>
                        <button class="button is-danger is-light" onclick="deleteCat(@(cat.Id))">Delete</button>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    

        <div class="container">
            <form method="post" enctype="multipart/form-data" asp-controller="Cat" asp-action="Post">
                <div class="columns">
                    <div class="column is-7"> 
                        <div class="field">
                            <label class="label">Name</label>
                            <div class="control">
                                <input class="input" name="name" type="text">
                            </div>
                        </div>

                        <div class="field">
                            <label class="label">Color</label>
                            <div class="control">
                                <input class="input" name="color" type="text">
                            </div>
                        </div>

                        <div class="field">
                            <label class="label">Age</label>
                            <div class="control">
                                <input class="input" name="age" type="number">
                            </div>
                        </div>

                        <div class="field">
                            <label class="label">Best Fail</label>
                            <div class="control">
                                <textarea class="textarea"  name="bestFail" placeholder="remember: Mio is the master of desaster ;-)"></textarea>
                            </div>
                        </div>
                    
                        <div class="control">
                            <button class="button is-link" type="submit">Submit</button>
                        </div>
                    </div>
                    <div class="column is-i"></div>
                    <div class="column is-4">
                        <img src="/img/flyingcat.jpg" alt="Flying cat">
                    </div>
                </div>
            </form>
        </div>
    </div>
}
else {
    <div class="text-center">
        <div class="container">
            <h1 class="is-size-2 has-text-weight-bold">Welcome to Mio's Cat Blog!</h1>

            <p>To be part of my lovely community, please log in.</p>
        </div>
    </div>
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
  
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CatBlog</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  <div class="container">
    <header>
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
              <a class="navbar-item brand" href="">CatBlog</a>
              <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
              </a>
            </div>
            <div id="navbarBasicExample" class="navbar-menu">
              <div class="navbar-start">
              </div>
              <div class="navbar-end">
                <div class="navbar-item">
                  <div class="buttons">
                    @if (SignInManager.IsSignedIn(User))
                    {
                    <a  class="button is-link" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
                    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post" >
                        <button  type="submit" class="button is-light">Logout</button>
                    </form>
                    }
                    else
                    {
                    <a class="button is-link" asp-area="Identity" asp-page="/Account/Register">Register</a>
                    <a class="button is-light" asp-area="Identity" asp-page="/Account/Login">Login</a>
                    }
                  </div>
                </div>
              </div>
            </div>
      </nav>
    </header>
    
    
    <partial name="_CookieConsentPartial" />
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
        
  
    <footer>
        <div class="content has-text-centered">
            <p>
              <strong>2019 - CatBlog</strong> © by <a href="https://www.linkedin.com/in/ilona-siegrist-34693a168/">Ilona Siegrist</a>. 
            </p>
        </div>
    </footer>
  </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    
</body>
</html>
























<!-- <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CatBlog</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3 navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CatBlog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Images</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - CatBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html> -->